### PR TITLE
fix tabs and typo in Catmandu::Exporter::CSV

### PR DESCRIPTION
**Pull request by jorol**

### CODE REVIEW

**Comment by vpeil** [comment]
this reminds me of an idea I've had last year at the hackathon:
we should use something like [.editorconfig](http://editorconfig.org/) or .perltidy... There are plugins for almost all popular editors. Then we can avoid reformatting, the editors would do the work for us :smiley:

**Comment by pietsch** [comment]
Interesting stuff. Let's do it!

**Comment by jorol** [comment]
We could add an `.perltidyrc` to our distributions, like:

```ini
-pbp     # Start with Perl Best Practices
-w       # Show all warnings
-iob     # Ignore old breakpoints
-l=78    # 78 characters per line
-mbl=2   # No more than 2 blank lines
-i=4     # Indentation is 4 columns
-ci=4    # Continuation indentation is 4 columns
-vt=0    # Less vertical tightness
-pt=2    # High parenthesis tightness
-bt=2    # High brace tightness
-sbt=2   # High square bracket tightness
-isbc    # Don't indent comments without leading space
```
Perhaps we should also define a .perlcriticrc...

**Comment by pietsch** [comment]
And then call it automatically from a git hook? https://github.com/mlawren/githook-perltidy

**Pull request merged**
