### PR TITLE
add fix include

### PR DESCRIPTION
**Pull request by nicolasfranck**
This fix enables you to include a fix file from another fix file.

### CODE REVIEW

**Comment by vpeil** [comment]
great! this one fixes #101

**Comment by nichtich** [comment]
is the path relative to the current directory or to the file that includes another file?
note that circular inclusion is not detected.

**Comment by nicolasfranck** [comment]
The path is relative to the executing script, no matter what depth.

Circular inclusion is indeed not detected. So be warned ;-).

**Comment by nicolasfranck** [comment]
Maybe fix file should be relative to one of the load paths?

```
#use default load_path (i.e. directory of the executing script)
#file must be located at $ENV{CWD}."/fixes/myfixes.txt"
Catmandu->fixer("include('fixes/myfixes.txt')");

#load fixes, located at /opt/catmandu-project/fixes/myfixes.txt
Catmandu->load("/opt/catmandu-project");
Catmandu->fixer("include('fixes/myfixes.txt')");

#look for 'fixes/myfixes.txt' in /opt/catmandu-project2, and if that fails in /opt/catmandu-project-1
Catmandu->load("/opt/catmandu-project2","/opt/catmandu-project-1");
Catmandu->fixer("include('fixes/myfixes.txt')");

#if "/opt/catmandu-project/fixes/myfixes2.txt" does not exists, the fix will fail
Catmandu->load("/opt/catmandu-project");
Catmandu->fixer("include('fixes/myfixes2.txt)");
```

That would mean, that this (current) behaviour should also be changed:

```
#looks for $ENV{CWD}."/fixes/myfixes.txt"
Catmandu->fixer('fixes/myfixes.txt')
```

**Comment by nichtich** [comment]
If run from command line I'd expect files to be relative to the current working directory but if `catmandu.yml` is loaded from another location it could be it's directory. Anyway, the documentation should be clear about locations. Fixes `cmd` and `lookup` also use/take a paths to this should be consistent.

**Comment by nicolasfranck** [comment]
The default load-path is always the current working directory, so that should be fine.

Indeed, if we choose for this lookup-feature, it should be implemented everywhere.

**Comment by vpeil** [comment]
the path stuff is a very sensitive issue to handle, e.g I've been running several times in issues while using Catmandu fixes and a Dancer webapp, depending on how you start the webapp and from which location and what you load in your app ... (ok, this is somehow off topic, just wanted to mention)

**Comment by nics** [comment]
No, it's not. It's only cwd when called from the catmandu script, 
otherwise it's the script directory, or one up if the script directory 
is 'bin'. Dancer does something equivalent.

**Comment by nicolasfranck** [comment]
See https://github.com/LibreCat/Catmandu/pull/173

**Pull request merged**
