### PR TITLE
introduce a new fix map to move several fields by a lookup table

### PR DESCRIPTION
**Pull request by vpeil**
in analogy the the lookup fix: this one lookups up in the table and moves the fields instead of changing the values.

### CODE REVIEW

**Comment by vpeil** [comment]
this one solves #67

**Comment by nichtich** [comment]
I'd like to rename this to `mapping` because `map` more likely refers to an individual row. We have fixes `marc_map` and `pica_map`, these could be extended with fixes `marc_mapping` and `pica_mapping` similar to this new fix. ok?

**Review by nics — COMMENTED** [review]
mapping is indeed better, looks good otherwise

**Comment by vpeil** [comment]
> mapping is indeed better, looks good otherwise

name of fix changed from map to mapping

**Comment by vpeil** [comment]
The tests fail for perl version 5.10 and 5.12, because one dependency module requires at least perl 5.14. Should we move on from these two versions?

**Comment by nichtich** [comment]
The failure was not caused by this PR but by https://github.com/LibreCat/Catmandu/issues/379

**Comment by nichtich** [comment]
I'd make deletion optional with option `delete: 0` (default: 1) so you can also copy instead of rename.

**Comment by vpeil** [comment]
> I'd make deletion optional with option `delete: 0` (default: 1) so you can also copy instead of rename.

@nichtich delete option could be misinterpreted by users: it could mean "delete all fields not in the mapping table" (as we use it in the lookup fix). Maybe find another option name?

**Comment by nichtich** [comment]
How about `keep` to not delete anything?

**Comment by vpeil** [comment]
@nics  @nichtich  Anything else that prevents it from a merge?

**Pull request merged**
