### PR TITLE
fixes #162. use JSON::MaybeXS

### LINKED ISSUE #162: Adding support for JSON::MaybeXS
Trying to use the fastest JSON parser available?

### PR DESCRIPTION
**Pull request by vpeil**

### CODE REVIEW

**Comment by nichtich** [comment]
what's the benefit? we used JSON::XS because there was a bug in JSON::PP. With JSON::MaybeXS we cannot control that the actual JSON library does not introduce the error.

**Comment by phochste** [comment]
The idea is that there are faster implementations available of JSON than JSON::XS. But the issue it quite complicated because Catmandu requires streaming capabilities for any JSON implementation. Not every package provides this.

**Comment by nichtich** [comment]
I doubt that JSON parsing is a performance bottleneck, sure there are better places for optimization.

**Comment by vpeil** [comment]
There is also another issue: How the express in a cpanfile that one JSON module out of three is required. That's actually the reason, why tests fail. There is noh JSON parser installed....
Any ideas? Otherwise, just move this PR to trash

**Comment by vpeil** [comment]
should we close this as well as #162 ? Looks like a lot of work for little effort....

**Pull request closed without merging**
