### PR TITLE
Search in store

### PR DESCRIPTION
**Pull request by nicolasfranck**

### CODE REVIEW

**Comment by nichtich** [comment]
How does this relate to [Catmandu::Fix::import](https://metacpan.org/pod/Catmandu::Fix::import) and [Catmandu::Fix::importer](https://metacpan.org/pod/Catmandu::Fix::importer)? We should try to keep consistent calling syntax and naming. The `data_path` option of `import` could also be supported by this fix. How about renaming it to `search` instead of `search_in_store`?

**Comment by nicolasfranck** [comment]
Catmandu::Fix::import starts from an importer, while search_in_store starts from a bag.

The main problem for the name is that now there is a fix "lookup" which does a "get" in a CSV,
and a "lookup_in_store" that does a "get" in a bag. Therefore renaming it to "search" should also
require "lookup" and "lookup_in_store" to be renamed.

**Comment by nichtich** [comment]
We definitely need aliases so we can securely rename fix functions. Otherwise the fix language will soon have a naming scheme like PHP :scream:

**Comment by nicolasfranck** [comment]
Here are my thoughts:

* "import" is ok: it does what it says
* "search_in_store" should be "search"
* "lookup_in_store" should be "get" or something similar ("lookup" is already reserved and cannot be reassigned to another function for backward compatibility). 
* "lookup" is in fact an "import" followed by a "get", which can be done by an in memory store like Catmandu::Store::Hash. To make this work we need the ability to import to a named store within a fix without configuration before?

**Pull request closed without merging**
